begin;

-- Test-only: allow authenticated to execute pg_temp helpers created in this
-- transaction. ROLLBACK at the end restores the hardened production defaults.
alter default privileges for role postgres
  grant execute on functions to anon, authenticated;
create function pg_temp.ok(v boolean,m text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'ASSERT: %',m; end if; end; $$;
create function pg_temp.err(q text,s text) returns void language plpgsql as $$ begin execute q; raise exception 'EXPECTED_ERROR: %',q; exception when others then if sqlstate <> s then raise; end if; end; $$;
create function pg_temp.t() returns uuid language sql as $$ select 'd1111111-aaaa-4aaa-8aaa-111111111111'::uuid $$;
create function pg_temp.loc() returns uuid language sql as $$ select 'd1111111-7777-4777-8777-111111111111'::uuid $$;
create function pg_temp.id(k text) returns uuid language sql as $$ select current_setting('test.'||k)::uuid $$;
insert into auth.users(id,aud,role,email) values ('d1111111-1111-4111-8111-111111111111','authenticated','authenticated','operating-writer@coost.test'),('d1111111-2222-4222-8222-111111111111','authenticated','authenticated','operating-reader@coost.test');
insert into public.tenants(id,name,status) values(pg_temp.t(),'Operating A','ACTIVE'),('d2222222-aaaa-4aaa-8aaa-111111111111','Operating B','ACTIVE');
insert into public.memberships(id,tenant_id,user_id,status) values('d1111111-3333-4333-8333-111111111111',pg_temp.t(),'d1111111-1111-4111-8111-111111111111','ACTIVE'),('d1111111-4444-4444-8444-111111111111',pg_temp.t(),'d1111111-2222-4222-8222-111111111111','ACTIVE');
insert into public.roles(id,tenant_id,key,name) values('d1111111-5555-4555-8555-111111111111',pg_temp.t(),'owner','Owner'),('d1111111-6666-4666-8666-111111111111',pg_temp.t(),'reader','Reader');
insert into public.membership_roles(tenant_id,membership_id,role_id) values(pg_temp.t(),'d1111111-3333-4333-8333-111111111111','d1111111-5555-4555-8555-111111111111'),(pg_temp.t(),'d1111111-4444-4444-8444-111111111111','d1111111-6666-4666-8666-111111111111');
insert into public.role_permissions(tenant_id,role_id,permission_key) select pg_temp.t(),'d1111111-5555-4555-8555-111111111111',unnest(array['food-service.costing.read','food-service.costing.write','inventory.write','purchasing.write']);
insert into public.role_permissions(tenant_id,role_id,permission_key) values(pg_temp.t(),'d1111111-6666-4666-8666-111111111111','food-service.costing.read');
insert into public.tenant_modules(tenant_id,module_key,enabled) select pg_temp.t(),unnest(array['food-service','inventory','purchasing','suppliers']),true;
insert into public.locations(id,tenant_id,name,status) values(pg_temp.loc(),pg_temp.t(),'Kitchen','ACTIVE'),('d1111111-8888-4888-8888-111111111111',pg_temp.t(),'Branch','ACTIVE'),('d2222222-7777-4777-8777-111111111111','d2222222-aaaa-4aaa-8aaa-111111111111','Foreign','ACTIVE');
insert into public.suppliers(id,tenant_id,name) values('d1111111-9999-4999-8999-111111111111',pg_temp.t(),'Supplier');
create function pg_temp.report(method text default 'NET_SALES',d date default '2026-01-01',loc uuid default null,c text default 'TRY') returns jsonb language sql as $$ select public.get_operating_profitability(pg_temp.t(),d,d,c,loc,method) $$;
create function pg_temp.sale(product uuid,q numeric,n numeric,d date default '2026-01-01') returns uuid language sql as $$ select public.upsert_menu_product_sales_fact(pg_temp.t(),pg_temp.loc(),d,product,q,n*1.2,n) $$;
create function pg_temp.expense(cat text,a numeric,loc uuid default null,c text default 'TRY') returns uuid language sql as $$ select public.create_operating_cost_entry(pg_temp.t(),'2026-01-01',c,cat,a,'Test expense',loc) $$;
set local role authenticated;
select set_config('request.jwt.claim.sub','d1111111-1111-4111-8111-111111111111',true);
select set_config('test.item',public.create_inventory_item(pg_temp.t(),'Ingredient','EACH')::text,true);
select set_config('test.missingitem',public.create_inventory_item(pg_temp.t(),'Unpriced','EACH')::text,true);
select set_config('test.unit',public.create_inventory_purchase_unit(pg_temp.t(),pg_temp.id('item'),'Each',1)::text,true);
select set_config('test.invoice',public.create_purchase_invoice_draft(pg_temp.t(),'d1111111-9999-4999-8999-111111111111','OP-1','2026-01-01','TRY',jsonb_build_array(jsonb_build_object('description','Ingredient','unit','Each','quantity',100,'unitPrice',10,'priceIncludesTax',false,'taxRate',20,'inventoryTracking','MAPPED','inventoryItemId',pg_temp.id('item'),'inventoryPurchaseUnitId',pg_temp.id('unit'))),pg_temp.loc())::text,true);
select public.post_purchase_invoice(pg_temp.t(),pg_temp.id('invoice'));
select set_config('test.recipe',public.create_recipe(pg_temp.t(),'Recipe','TRY',1,jsonb_build_array(jsonb_build_object('inventoryItemId',pg_temp.id('item'),'quantityBase',1)))::text,true);
select set_config('test.missing',public.create_recipe(pg_temp.t(),'Missing','TRY',1,jsonb_build_array(jsonb_build_object('inventoryItemId',pg_temp.id('missingitem'),'quantityBase',1)))::text,true);
select set_config('test.a',public.create_menu_product(pg_temp.t(),'Alpha',pg_temp.id('recipe'),'TRY',120,20,'LAST_PURCHASE',25,null,null,20)::text,true);
select set_config('test.b',public.create_menu_product(pg_temp.t(),'Beta',pg_temp.id('recipe'),'TRY',120,20,'WEIGHTED_PURCHASE',30,null,null,20)::text,true);
select set_config('test.c',public.create_menu_product(pg_temp.t(),'Gamma',pg_temp.id('recipe'),'TRY',120,20)::text,true);
select set_config('test.incomplete',public.create_menu_product(pg_temp.t(),'Incomplete',pg_temp.id('missing'),'TRY',120,20)::text,true);
select pg_temp.err($q$select public.create_menu_product(pg_temp.t(),'Bad',pg_temp.id('recipe'),'TRY',1,0,p_target_operating_margin_pct=>100)$q$,'22023');
select pg_temp.err($q$select public.create_menu_product(pg_temp.t(),'Bad',pg_temp.id('recipe'),'TRY',1,0,p_target_operating_margin_pct=>0)$q$,'22023');
select public.update_menu_product(pg_temp.t(),pg_temp.id('a'),'Alpha',pg_temp.id('recipe'),'TRY',120,20,'LAST_PURCHASE','ACTIVE',25,null,null,30);
select pg_temp.ok((select p->>'targetFoodCostPct'='25.000' and (p->>'targetOperatingMarginPct')::numeric=30 from jsonb_array_elements(public.get_menu_costing_overview(pg_temp.t())->'products') p where p->>'id'=pg_temp.id('a')::text),'independent targets update');
select public.update_menu_product(pg_temp.t(),pg_temp.id('a'),'Alpha',pg_temp.id('recipe'),'TRY',120,20,'LAST_PURCHASE','ACTIVE',25,null,null,20);
select set_config('test.fact',pg_temp.sale(pg_temp.id('a'),1,50)::text,true);
select pg_temp.ok(pg_temp.sale(pg_temp.id('a'),2,100)=pg_temp.id('fact'),'daily upsert stable identity');
select pg_temp.sale(pg_temp.id('b'),1,50);
select pg_temp.sale(pg_temp.id('c'),1,0);
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),2,100)$q$,'22023');
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),0,1)$q$,'22023');
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),-1,0)$q$,'22023');
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),0.00001,0)$q$,'22023');
select pg_temp.err($q$select public.upsert_menu_product_sales_fact(pg_temp.t(),pg_temp.loc(),'2026-01-01',pg_temp.id('a'),1,-1,0)$q$,'22023');
select pg_temp.err($q$select public.upsert_menu_product_sales_fact(pg_temp.t(),'d2222222-7777-4777-8777-111111111111','2026-01-01',pg_temp.id('a'),1,1,1)$q$,'22023');
select set_config('test.fixed',pg_temp.expense('FIXED_OVERHEAD',30)::text,true);
select pg_temp.expense('LABOR',15,pg_temp.loc());
select pg_temp.expense('POS_COMMISSION',3);
select pg_temp.expense('OTHER_VARIABLE',12);
select set_config('test.void',pg_temp.expense('FIXED_OVERHEAD',999)::text,true);
select public.update_operating_cost_entry(pg_temp.t(),pg_temp.id('void'),'2026-01-01','TRY','LABOR',1000,'Updated expense');
select pg_temp.err($q$select public.update_operating_cost_entry(pg_temp.t(),pg_temp.id('void'),'2026-01-01','TRY','LABOR',1000,'Updated expense')$q$,'22023');
select public.void_operating_cost_entry(pg_temp.t(),pg_temp.id('void'));
select pg_temp.err($q$select public.void_operating_cost_entry(pg_temp.t(),pg_temp.id('void'))$q$,'55000');
select pg_temp.err($q$select public.update_operating_cost_entry(pg_temp.t(),pg_temp.id('void'),'2026-01-01','TRY','LABOR',1,'Changed')$q$,'55000');
select pg_temp.err($q$select pg_temp.expense('LABOR',0)$q$,'22023');
select pg_temp.err($q$select pg_temp.expense('LABOR',-1)$q$,'22023');
select pg_temp.err($q$select pg_temp.expense('BAD',1)$q$,'22023');
select pg_temp.err($q$select pg_temp.expense('LABOR',1.001)$q$,'22023');
select pg_temp.err($q$select pg_temp.expense('LABOR',1,null,'bad')$q$,'22023');
select pg_temp.expense('LABOR',777,null,'EUR');
select pg_temp.ok((pg_temp.report()->'summary'->>'netSales')::numeric=150 and (pg_temp.report()->'summary'->>'estimatedRecipeCost')::numeric=40 and (pg_temp.report()->'summary'->>'directContribution')::numeric=110 and (pg_temp.report()->'summary'->>'allocatedOperatingContribution')::numeric=50,'summary and no double count');
select pg_temp.ok(abs((pg_temp.report()->'summary'->>'allocatedOperatingMarginPct')::numeric-100::numeric/3)<1e-12,'operating margin');
select pg_temp.ok((select (p->>'estimatedRecipeCost')::numeric=20 and (p->>'directContribution')::numeric=80 and abs((p->>'allocatedOperatingCost')::numeric-40)<1e-12 and abs((p->>'allocatedOperatingContribution')::numeric-40)<1e-12 and abs((p->>'targetDifferencePp')::numeric-20)<1e-12 and abs((p->>'suggestedNetPriceAtTarget')::numeric-37.5)<1e-12 and abs((p->>'suggestedGrossPriceAtTarget')::numeric-45)<1e-12 from jsonb_array_elements(pg_temp.report()->'products') p where p->>'productId'=pg_temp.id('a')::text),'product formulas target net and gross');
select pg_temp.ok((select (p->>'allocatedOperatingCost')::numeric=30 from jsonb_array_elements(pg_temp.report('QUANTITY')->'products') p where p->>'productId'=pg_temp.id('a')::text),'quantity allocation');
select pg_temp.ok((select abs((p->>'allocatedOperatingCost')::numeric-20)<1e-12 from jsonb_array_elements(pg_temp.report('EQUAL')->'products') p where p->>'productId'=pg_temp.id('c')::text),'equal includes zero sales');
do $$ declare method text; r jsonb; begin
  foreach method in array array['NET_SALES','QUANTITY','EQUAL'] loop
    r:=pg_temp.report(method);
    perform pg_temp.ok((select sum((p->>'allocationWeight')::numeric)=1 and sum((p->>'allocatedFixedOverhead')::numeric)=30 and sum((p->>'allocatedLabor')::numeric)=15 and sum((p->>'allocatedPosCommission')::numeric)=3 and sum((p->>'allocatedOtherVariable')::numeric)=12 and sum((p->>'allocatedOperatingCost')::numeric)=60 from jsonb_array_elements(r->'products') p),'exact category reconciliation '||method);
  end loop;
end $$;
select pg_temp.expense('FIXED_OVERHEAD',90,'d1111111-8888-4888-8888-111111111111');
select pg_temp.ok((pg_temp.report('NET_SALES','2026-01-01',pg_temp.loc())->'summary'->'operatingCosts'->>'total')::numeric=60 and (pg_temp.report()->'summary'->'operatingCosts'->>'total')::numeric=150,'location includes shared costs and excludes other branch');
select pg_temp.ok((pg_temp.report('NET_SALES','2026-01-01',null,'EUR')->'summary'->'operatingCosts'->>'total')::numeric=777,'currency isolation');
select pg_temp.sale(pg_temp.id('incomplete'),1,50,'2026-01-02');
select pg_temp.sale(pg_temp.id('a'),1,50,'2026-01-02');
select pg_temp.ok(pg_temp.report('NET_SALES','2026-01-02')->'summary'->>'estimatedRecipeCost' is null and pg_temp.report('NET_SALES','2026-01-02')->'summary'->>'directContribution' is null and pg_temp.report('NET_SALES','2026-01-02')->'summary'->>'allocatedOperatingContribution' is null,'incomplete summary propagates');
select pg_temp.ok((select p->>'estimatedRecipeCost' is null and p->>'allocatedOperatingContribution' is null and p->>'suggestedGrossPriceAtTarget' is null from jsonb_array_elements(pg_temp.report('NET_SALES','2026-01-02')->'products') p where p->>'productId'=pg_temp.id('incomplete')::text),'missing cost never zero');
select pg_temp.sale(pg_temp.id('a'),1,0,'2026-01-03');
select pg_temp.ok(pg_temp.report('NET_SALES','2026-01-03')->>'allocationStatus'='ZERO_ALLOCATION_BASE' and pg_temp.report('QUANTITY','2026-01-03')->>'allocationStatus'='READY','zero net denominator');
select pg_temp.sale(pg_temp.id('a'),0,0,'2026-01-04');
select pg_temp.ok(pg_temp.report('QUANTITY','2026-01-04')->>'allocationStatus'='ZERO_ALLOCATION_BASE' and pg_temp.report('EQUAL','2026-01-04')->>'allocationStatus'='READY','zero quantity denominator');
select pg_temp.ok((pg_temp.report('EQUAL','2026-01-04')->'products'->0)->>'allocatedOperatingCostPerUnit' is null and (pg_temp.report('EQUAL','2026-01-04')->'products'->0)->>'suggestedNetPriceAtTarget' is null,'zero quantity price undefined');
select public.create_operating_cost_entry(pg_temp.t(),'2026-01-05','TRY','LABOR',10,'No sales');
select pg_temp.ok(pg_temp.report('NET_SALES','2026-01-05')->>'allocationStatus'='NO_SALES' and (pg_temp.report('NET_SALES','2026-01-05')->'summary'->'operatingCosts'->>'total')::numeric=10 and pg_temp.report('NET_SALES','2026-01-05')->'summary'->>'allocatedOperatingContribution' is null,'no sales retains expense');
select pg_temp.ok((public.get_operating_profitability(pg_temp.t(),'2026-01-01','2026-01-04','TRY')->'summary'->>'netSales')::numeric=250,'inclusive period');
select pg_temp.err($q$select public.get_operating_profitability(pg_temp.t(),'2026-02-01','2026-01-01','TRY')$q$,'22023');
select pg_temp.err($q$select public.get_operating_profitability(pg_temp.t(),'2025-01-01','2026-01-02','TRY')$q$,'22023');
select pg_temp.err($q$select pg_temp.report('BAD')$q$,'22023');
select pg_temp.ok((select count(*)=1 from jsonb_array_elements(public.get_operating_data(pg_temp.t(),'2026-01-01','2026-01-01','TRY')->'expenses') e where e->>'status'='VOID'),'void visible in history');
reset role;
select pg_temp.ok((select count(*)=1 from public.menu_product_sales_facts where id=pg_temp.id('fact')),'daily identity');
select pg_temp.ok((select count(*)=2 from public.audit_logs where entity_id=pg_temp.id('fact')),'create update audit no no-op audit');
select pg_temp.ok(exists(select 1 from public.audit_logs where entity_id=pg_temp.id('fact') and action='MENU_SALES_FACT_UPDATED' and (metadata->'old'->>'quantity')::numeric=1 and (metadata->'new'->>'quantity')::numeric=2),'audit old and new');
select pg_temp.ok(not exists(select 1 from public.finance_transactions where tenant_id=pg_temp.t()) and not exists(select 1 from public.finance_entries where tenant_id=pg_temp.t()),'no finance movement');
select pg_temp.err($q$delete from public.operating_cost_entries where id=pg_temp.id('fixed')$q$,'55000');
select pg_temp.err($q$delete from public.menu_product_sales_facts where id=pg_temp.id('fact')$q$,'55000');
select pg_temp.err($q$update public.operating_cost_entries set amount=1 where id=pg_temp.id('void')$q$,'55000');
select pg_temp.err($q$insert into public.menu_product_sales_facts(tenant_id,location_id,sale_date,menu_product_id,currency_code,quantity,gross_sales,net_sales,source_type) values(pg_temp.t(),pg_temp.loc(),'2026-01-01',pg_temp.id('a'),'TRY',1,1,1,'MANUAL')$q$,'23505');
select pg_temp.err($q$insert into public.menu_product_sales_facts(tenant_id,location_id,sale_date,menu_product_id,currency_code,quantity,gross_sales,net_sales,source_type) values(pg_temp.t(),pg_temp.loc(),'2026-02-01',pg_temp.id('a'),'EUR',1,1,1,'MANUAL')$q$,'23503');
insert into public.menu_product_sales_facts(tenant_id,location_id,sale_date,menu_product_id,currency_code,quantity,gross_sales,net_sales,source_type) values(pg_temp.t(),pg_temp.loc(),'2026-02-01',pg_temp.id('a'),'TRY',1,1,1,'SALES_APP');
insert into public.operating_cost_entries(id,tenant_id,occurred_on,currency_code,category,amount,description,source_type) values('d1111111-abcd-4abc-8abc-111111111111',pg_temp.t(),'2026-02-01','TRY','LABOR',1,'External','STAFF');
delete from public.role_permissions where role_id='d1111111-5555-4555-8555-111111111111' and permission_key not like 'food-service.%';
set local role authenticated;
select pg_temp.expense('LABOR',1);
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),2,2,'2026-02-01')$q$,'55000');
select pg_temp.err($q$select public.void_operating_cost_entry(pg_temp.t(),'d1111111-abcd-4abc-8abc-111111111111')$q$,'55000');
select pg_temp.err($q$select public.update_operating_cost_entry(pg_temp.t(),'d1111111-abcd-4abc-8abc-111111111111','2026-02-01','TRY','LABOR',2,'External')$q$,'55000');
select pg_temp.err($q$select public.get_operating_profitability('d2222222-aaaa-4aaa-8aaa-111111111111','2026-01-01','2026-01-01','TRY')$q$,'42501');
select pg_temp.err($q$select public.get_operating_data('d2222222-aaaa-4aaa-8aaa-111111111111','2026-01-01','2026-01-01','TRY')$q$,'42501');
select pg_temp.err($q$select public.void_operating_cost_entry('d2222222-aaaa-4aaa-8aaa-111111111111',pg_temp.id('fixed'))$q$,'42501');
select pg_temp.err($q$select * from public.menu_product_sales_facts$q$,'42501');
select pg_temp.err($q$select * from public.operating_cost_entries$q$,'42501');
select set_config('request.jwt.claim.sub','d1111111-2222-4222-8222-111111111111',true);
select pg_temp.ok(pg_temp.report()->>'allocationStatus'='READY','reader report');
select pg_temp.err($q$select pg_temp.sale(pg_temp.id('a'),9,9)$q$,'42501');
select pg_temp.err($q$select pg_temp.expense('LABOR',1)$q$,'42501');
select pg_temp.err($q$select public.update_operating_cost_entry(pg_temp.t(),pg_temp.id('fixed'),'2026-01-01','TRY','LABOR',1,'Denied')$q$,'42501');
select pg_temp.err($q$select public.void_operating_cost_entry(pg_temp.t(),pg_temp.id('fixed'))$q$,'42501');
reset role;
update public.tenant_modules set enabled=false where tenant_id=pg_temp.t() and module_key='food-service';
set local role authenticated;
select pg_temp.err($q$select pg_temp.report()$q$,'42501');
select pg_temp.err($q$select public.get_operating_data(pg_temp.t(),'2026-01-01','2026-01-01','TRY')$q$,'42501');
select set_config('request.jwt.claim.sub','d1111111-1111-4111-8111-111111111111',true);
select pg_temp.err($q$select pg_temp.expense('LABOR',1)$q$,'42501');
select set_config('request.jwt.claim.sub','',true);
select pg_temp.err($q$select pg_temp.report()$q$,'42501');
set local role anon;
select pg_temp.err($q$select pg_temp.report()$q$,'42501');
reset role;
do $$ declare t text; f record; begin
  foreach t in array array['menu_product_sales_facts','operating_cost_entries'] loop
    perform pg_temp.ok((select relrowsecurity from pg_class where oid=('public.'||t)::regclass),'RLS');
    perform pg_temp.ok(not has_table_privilege('authenticated','public.'||t,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE') and not has_table_privilege('anon','public.'||t,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),'direct grants revoked');
  end loop;
  for f in select p.* from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('get_operating_profitability','get_operating_data','upsert_menu_product_sales_fact','create_operating_cost_entry','update_operating_cost_entry','void_operating_cost_entry') loop
    perform pg_temp.ok(f.prosecdef and 'search_path=""'=any(f.proconfig),'secure definer');
    perform pg_temp.ok(not has_function_privilege('anon',f.oid,'EXECUTE') and has_function_privilege('authenticated',f.oid,'EXECUTE'),'RPC grants');
    perform pg_temp.ok(not exists(select 1 from aclexplode(f.proacl) where grantee=0 and privilege_type='EXECUTE'),'PUBLIC revoked');
  end loop;
end $$;
rollback;
do $$ begin if exists(select 1 from auth.users where email like 'operating-%@coost.test') or exists(select 1 from public.tenants where id in ('d1111111-aaaa-4aaa-8aaa-111111111111','d2222222-aaaa-4aaa-8aaa-111111111111')) then raise exception 'RESIDUAL_FIXTURES'; end if; end $$;
select 'PASS - OPERATING PROFITABILITY' result,(select count(*) from auth.users where email like 'operating-%@coost.test') residual_test_users,(select count(*) from public.tenants where id in ('d1111111-aaaa-4aaa-8aaa-111111111111','d2222222-aaaa-4aaa-8aaa-111111111111')) residual_test_tenants;
